import type { SimulationConfig } from './types';

export const defaultConfig: SimulationConfig = {
  nodeCount: 1500,
  width: 1180,
  height: 760,
  seed: 20260430,
  topology: 'spatial-local',
  initialDistribution: 'uniform-field',
  initialFieldMargin: 34,
  initialJitter: 0.74,
  initialVelocityScale: 0.035,
  initialLocalRadius: 92,
  averageDegree: 6,
  energyPerNode: 1,
  ctRatio: 8,
  resonanceCoupling: 1.68,
  impedanceCoupling: 0.72,
  linkAdaptationRate: 1.24,
  resonanceThreshold: 0.68,
  linkBreakThreshold: 0.035,
  impedanceSpread: 0.62,
  entropyLoosening: 0.36,
  entangledPairs: 8,
  maxLinks: 12000,
  timeScale: 1,
  particleThreshold: 0.58,
  minParticleNodes: 8,
  massBindingRate: 1.42,
  strongScale: 1.18,
  electromagneticScale: 0.58,
  weakScale: 0.38,
  gravityScale: 0.42,
  graphFormationAttempts: 95,
  showForceView: 'all',

  planckLengthM: 1.616255e-35,
  planckEnergyJ: 1.9561e9,
  particleEffectiveRadiusM: 1e-19,
  targetParticlePreset: 'electron',
  customTargetRestEnergyJ: 8.1871057769e-14,
  targetParticleCountInView: 1,
  nodesPerParticleBase: 1000,
  completeParticleFraction: 0.85,
  stableParticleAge: 16,
  adaptiveNodeRendering: true,

  disableResonanceTerm: false,
  disableImpedanceTerm: false,
  disableColorTerm: false,
  disableEnergyCorrection: false,
  randomBondModel: false,

  forceIsolationMode: 'none',
  disableGravityLike: false,
  disableDamping: false,
  blockCenterPull: true,
  forbidMeanPositionLock: true,

  enableEventCirculation: true,
  eventTriggerThreshold: 0.42,
  eventPulseDecay: 0.88,
  eventCouplingStrength: 1.0,
  activityDecay: 0.965,
  continuityGain: 0.11,
  continuityDecay: 0.026,
  cycleBondThreshold: 0.58,
  loopSampleCount: 220,
  loopClosureTolerance: 0.72,
  requireCycleForParticle: true,

  enableResonancePrioritySearch: true,
  priorityCandidateSamples: 28,
  priorityHistoryWeight: 0.16,
  priorityLoopWeight: 0.18,
  testPulseStrength: 0.22,
  failedEdgeDecay: 0.022,
  showPriorityCandidates: true
};
