import type { SimulationConfig } from './types';

export const defaultConfig: SimulationConfig = {
  nodeCount: 1500,
  width: 1180,
  height: 760,
  seed: 20260430,
  topology: 'spatial-local',
  initialDistribution: 'uniform-field',
  initialFieldMargin: 34,
  initialJitter: 0.74,
  initialVelocityScale: 0.055,
  initialLocalRadius: 92,
  averageDegree: 6,
  energyPerNode: 1,
  ctRatio: 8,
  resonanceCoupling: 1.68,
  impedanceCoupling: 0.72,
  linkAdaptationRate: 1.24,
  resonanceThreshold: 0.60,
  linkBreakThreshold: 0.035,
  impedanceSpread: 0.62,
  entropyLoosening: 0.36,
  entangledPairs: 8,
  maxLinks: 9000,
  timeScale: 1.85,
  particleThreshold: 0.50,
  minParticleNodes: 5,
  massBindingRate: 1.25,
  strongScale: 1.18,
  electromagneticScale: 0.58,
  weakScale: 0.38,
  gravityScale: 0.42,
  graphFormationAttempts: 36,
  showForceView: 'event',

  planckLengthM: 1.616255e-35,
  planckEnergyJ: 1.9561e9,
  planckTimeS: 5.3906e-44,
  timeCompressionFactor: 3.437e11,
  crossingVisualSeconds: 300,
  visualStepsPerSecond: 60,
  measuredStepsPerSecond: 0,
  autoCalibrateTimeCompression: true,
  particleEffectiveRadiusM: 1e-19,
  targetParticlePreset: 'electron',
  customTargetRestEnergyJ: 8.1871057769e-14,
  targetParticleCountInView: 1,
  nodesPerParticleBase: 100,
  completeParticleFraction: 0.65,
  stableParticleAge: 16,
  adaptiveNodeRendering: true,

  disableResonanceTerm: false,
  disableImpedanceTerm: false,
  disableColorTerm: false,
  disableEnergyCorrection: false,
  randomBondModel: false,

  forceIsolationMode: 'none',
  disableGravityLike: false,
  disableDamping: false,
  blockCenterPull: true,
  forbidMeanPositionLock: true,

  enableEventCirculation: true,
  eventTriggerThreshold: 0.052,
  eventPulseDecay: 0.94,
  eventCouplingStrength: 1.18,
  activityDecay: 0.982,
  continuityGain: 0.085,
  continuityDecay: 0.028,
  cycleBondThreshold: 0.44,
  loopSampleCount: 160,
  loopClosureTolerance: 1.30,
  requireCycleForParticle: true,

  enableResonancePrioritySearch: true,
  priorityCandidateSamples: 36,
  priorityHistoryWeight: 0.16,
  priorityLoopWeight: 0.18,
  testPulseStrength: 0.24,
  failedEdgeDecay: 0.012,
  showPriorityCandidates: true,

  enablePulseGovernor: true,
  targetPulseDensity: 0.038,
  maxVisiblePulses: 190,
  pulseEmissionBudgetPerStep: 18,
  pulseThrottleStrength: 0.72,
  pulseVisualLifetime: 64,
  pulseVisualSpeed: 0.62,
  minPulseIntensity: 0.045,

  enableCoarseEventField: true,
  showCoarseEventField: true,
  coarseGridCols: 36,
  coarseGridRows: 24,
  coarseFieldSmoothing: 0.72,
  coarseFieldIntensity: 1.15,
  showFieldParticlesOnly: false,

  performanceMode: true,
  renderSnapshotFps: 24,
  heavyMetricInterval: 5,
  particleDetectionInterval: 3,
  cycleDetectionInterval: 3,
  coarseFieldInterval: 3,
  maxRenderedEdges: 900,
  maxRenderedNodes: 800,

  engineStepsPerFrame: 5,
  maxCatchUpSteps: 12,
  simulationSpeedMultiplier: 3.2,
  showFormationLabels: false,
  showInteractionLines: false,
  maxFormationWaves: 12,
  maxInteractionLines: 80,
  edgeAlphaScale: 0.36,
  massBondRenderRatio: 0.12,
  cycleBondRenderRatio: 0.85,

  enableAntiSaturation: true,
  targetEventActivity: 0.72,
  eventSaturationDamping: 0.38,
  maxParticleComponentFactor: 1.8,
  splitLargeParticleComponents: true,

  enableStableVerifier: true,
  stableVerifierWindow: 90,
  stableMinSurvivalTicks: 120,
  stableMinCrossingProgress: 0.25,
  stableMinCycleContinuity: 0.72,
  stableMinInternalBondRatio: 0.54,
  stableMaxExternalBondRatio: 0.46,
  stableVerifierScoreThreshold: 0.68,
  verifierMergeDistance: 74,
  verifierDecayGrace: 80
};
